heat_template_version: 2014-10-16

#
# You have to prepare two parameters before you can start this stack:
# 1. a public network id. 
# 2. a reserved, but not assigned ip address from this net.
# you can deploy this template using the following command:
#
# you can get a list of Network-IDs with the following command:
# 'neutron net-list'
# you get a list of floating IPs with this command:
# 'neutron floatingip-list'
#
# 'heat stack-create -f example.yaml -P key_name=<my_key> -P public_network_id=<networkID> -P fixed_ip=<ipID> <stack_name>'
#
# after successful stack creation you can login with 
# ssh -l ec2-user <externalIP> 
# 

description: Template to deploy a single compute instance
  with external network (login will be possible through vnc console and via SSH).
  Use it with caution, you break the most important feature in OpenStack... to 
  deploy your setup more than once. 

parameters:
 key_name:
  type: string
 public_network_id:
  type: string
 fixed_ip:
  type: string


resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: Ubuntu 14.04 sys11-cloudimg amd64
      flavor: m1.tiny
      networks:
        - port: { get_resource: example_port }

  example_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: example_net}

  example_net:
    type: OS::Neutron::Net
    properties: 
      name: example-net

  example_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: example_subnet
      dns_nameservers:
        - 37.123.105.116
        - 37.123.105.117
      network_id: {get_resource: example_net}
      ip_version: 4
      cidr: 10.0.0.0/24
      allocation_pools:
      - {start: 10.0.0.10, end: 10.0.0.250}

#  example_floating_ip:
#    type: OS::Neutron::FloatingIP
#    properties:
#      floating_network: { get_param: public_network_id }
#      port_id: { get_resource: example_port }

  associate_my_ip:
    type: OS::Nova::FloatingIPAssociation
    depends_on: my_instance
    properties:
      floating_ip: { get_param: fixed_ip }
      server_id: { get_resource: my_instance }
