heat_template_version: 2014-10-16

# Start this template using
# 'heat stack-create -f singleServerWithVolume.yaml'.
# You need to adjust "key_name" and "floating_network".

description: creates an empty volume for later use 

parameters:
 volume_size:
  type: string
  default: 300
 volume_name:
  type: string
  default: syselevenVolume

resources:
# create an empty volume 
  my_volume:
   type: OS::Cinder::Volume
   properties:
     description: a fresh volume
     name: { get_param: volume_name }
     size: { get_param: volume_size } 

