heat_template_version: 2016-04-08

description: Create network, subnet, router, ports and reserve IPs for later use

parameters:
  public_network:
    type: string
    default: ext-net 
  number_of_fips: 
    type: number
    default: 1
    description: Defines the number of reserved floating IPs.
    constraints:
       – integer: “”
       description: >
          Must be a number (boolean).

resources:
  fips:
      type: OS::Heat::ResourceGroup
      properties:
        count: { get_param: number_of_fips }
        resource_def: 
          type: reserve_fip.yaml
          properties:
            public_network: { get_param: public_network }