heat_template_version: 2014-10-16

#
# you can deploy this template using the following command:
# 'heat stack-create -f example.yaml -P key_name=<my_key> -P public_network_id=<networkID> -P ip_whitelist=<yourOfficeIP> <stack_name>'
#
# after successful stack creation you can login with 
# ssh -l ec2-user <externalIP> 
# 


description: Simple template to deploy a single compute instance
  with external network and associated security group.

parameters:
 key_name:
  type: string
 public_network_id:
  type: string
 ip_whitelist:
  type: string
  description: ip address or range in CIDR


resources:
  allow_static_ip:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming traffic only from specified IP.
      name: allow incoming traffic, tcp
      rules: [{direction: ingress, remote_ip_prefix: {get_param: ip_whitelist}, port_range_min: 0, port_range_max: 65535, protocol: tcp} ]

  secured_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: Ubuntu 14.04 sys11-cloudimg amd64
      flavor: m1.tiny
      networks:
        - port: { get_resource: example_port }

  example_port:
    type: OS::Neutron::Port
    properties:
      security_groups: [ get_resource: allow_static_ip ]
      network_id: { get_resource: example_net}

  example_net:
    type: OS::Neutron::Net
    properties: 
      name: example-net

  example_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: example_subnet
      dns_nameservers:
        - 37.123.105.116
        - 37.123.105.117
      network_id: {get_resource: example_net}
      ip_version: 4
      cidr: 10.0.0.0/24
      allocation_pools:
      - {start: 10.0.0.10, end: 10.0.0.250}

  example_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network_id }
      port_id: { get_resource: example_port }
