heat_template_version: 2015-04-30

description: Simple template to deploy two nodes with NFS share

parameters:
  number_nfsclients: 
    type: string
    default: 2
  public_network:
    type: string
    default: ext-net 
  volume_id:
    type: string
    default: 
  ssh-keys:
    type: comma_delimited_list
    default: 
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDN7WgiiXGQju8PlZ2IVoQygxeLzxvt2baZx9Q1JmfHed6Pxz+yiibbWiZIMDYiu76FSf6SENoUdSb56jcuFv4CCfu1lnLa3p/si/ic7BlDeIs6754cqdQTMlHShPw9z69cJKdd0qsA5KPBL7tEzCUWrRDidsiHza9cj/mlZ7w5X6+BUhXYa/0UK6cjkYD/T7qHhgYAGCalhwRIIPdoFhllkGaoO5r0gUgvkv1PFpK7psNfuxbuA4th0gU4Qhgj8hTpmcRFceneIwG9ZpEIbhbfyQcA3pPSZFDGsdcnDhHMHXHZsjGLca1lXDh7izn3t8fHLXAjwMnw5OdsNu6vARk+JZsZprrwSi++WWd43KUeGNdr5KLgHQDaNiLhgBKwZk+4ZpK1BAl4PZidX6P+idu4qWHNEv49yzxfI+puPbwhNBtWIrehZVKSah9/ALYtDyYBtMRyF9i9fW4O17Ov5dR10vrq4Mm6NlBJynCFjMY6z8hZFZCHc3QnPLCwfIeRH2PRMJonF5+wsyc4kxCwqK1HLsvwSFcAVdsEtFeppEEq5/WjDiv6sb62h+lckL/hXm+Y3rKULpEoHuVl/BX/rwCI1c6ES6asLQ3ZkEYo/0s3FnzZlu2qEYERddUAmzunAPx3fzcMjNUsEmpZS1uXUOFIenL+rj1kSmDfb90fQQRnnQ== dschwabe@dschwabe'

resources:
  syseleven_net:
    type: OS::Neutron::Net
    properties: 
      name: syseleven-net

  syseleven_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: syseleven_subnet
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      network: {get_resource: syseleven_net}
      ip_version: 4
      cidr: 10.10.10.0/8
      allocation_pools:
      - {start: 10.10.10.2, end: 10.10.10.10}

  syseleven_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": { get_param: public_network }}

  router_subnet_connect:
    type: OS::Neutron::RouterInterface
    depends_on: [ syseleven_subnet, syseleven_router, syseleven_net ]
    properties:
      router: { get_resource: syseleven_router }
      subnet: { get_resource: syseleven_subnet }

  ### NFS Node as resource group ###
  #######################
  nfs_nodes:
    type: OS::Heat::ResourceGroup
    depends_on: [ syseleven_net, syseleven_subnet, router_subnet_connect ]
    properties:
      count: 1
      resource_def: 
        type: nfs-server.yaml
        properties:
          name: nfs-server%index%
          syseleven_net: { get_resource: syseleven_net }
          ssh-keys: { get_param: ssh-keys }
          public_network: { get_param: public_network }
          volume_id: { get_param: volume_id } 

  ### Server Node as resource group ###
  #######################
  server_group:
    type: OS::Heat::ResourceGroup
    depends_on: [ syseleven_net, syseleven_subnet, router_subnet_connect ]
    properties:
      count: { get_param: number_nfsclients }
      resource_def: 
        type: nfs-client.yaml
        properties:
          name: nfs-client%index%
          syseleven_net: { get_resource: syseleven_net }
          ssh-keys: { get_param: ssh-keys }

