heat_template_version: 2016-04-08

description: network topology in dbl

resources:

  dbl_net:
    type: OS::Neutron::Net
    properties: 
      name: dbl-net

  dbl_subnet:
    type: OS::Neutron::Subnet
    depends_on: [ dbl_net ]
    properties:
      name: dbl_subnet
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      network: {get_resource: dbl_net}
      ip_version: 4
      cidr: 192.168.3.0/24
      allocation_pools:
      - {start: 192.168.3.10, end: 192.168.3.250}

  dbl_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": ext-net }

  dbl_router_subnet_connect:
    type: OS::Neutron::RouterInterface
    depends_on: [ dbl_router, dbl_subnet ]
    properties:
      router: { get_resource: dbl_router }
      subnet: { get_resource: dbl_subnet }

  testmachine-dbl:
    type: OS::Heat::Stack
    properties:
      context:
        region_name: dbl
      parameters: 
        network_id: { get_resource: dbl_net }
      template: { get_file: testserver.yaml }

outputs:
# output subnet-addres, subnet-id and router-id
  subnet_address:
    value: {get_attr: [dbl_subnet, cidr] }
  router_id:
    value: { get_resource: dbl_router }
  subnet_id:
    value: { get_resource: dbl_subnet }
  external_gateway:
    value: { get_attr: [dbl_router, external_gateway_info, external_fixed_ips, 0, ip_address] }
