heat_template_version: 2016-04-08

description: vpn site to site connection

parameters:
  gateway_ip:
    type: string
  vpnservice_id:
    type: string
  shared_secret:
    type: string
  peer_subnet_address:
    type: string
    


resources:

  IKEPolicy:
    type: OS::Neutron::IKEPolicy
    properties:
      name: IKEPolicy cbk
      description: Key exchange policy for site cbk
      auth_algorithm: sha1
      encryption_algorithm: aes-128
      phase1_negotiation_mode: main
      lifetime: 
        units: seconds
        value: 3600
      pfs: group14
      ike_version: v1

  IPsecPolicy: 
    type: OS::Neutron::IPsecPolicy
    properties:
      name: IPSecPolicy cbk
      description: IPSec policy for site cbk
      auth_algorithm: sha1
      encryption_algorithm: aes-128
      transform_protocol: esp
      lifetime: 
        units: seconds
        value: 3600
      pfs: group14
      encapsulation_mode: tunnel

  IPsecSiteConnection:
    type: OS::Neutron::IPsecSiteConnection
    properties:
      name: IPsecSiteConnection cbk
      description: IPSec Connection cbk
      peer_address: { get_param: gateway_ip }
      peer_id: { get_param: gateway_ip }
      peer_cidrs: 
        - { get_param: peer_subnet_address }
      mtu: 1500
      psk: { get_param: shared_secret }
      initiator: bi-directional
      admin_state_up: true
      ikepolicy_id: { get_resource: IKEPolicy }
      ipsecpolicy_id: { get_resource: IPsecPolicy }
      vpnservice_id: { get_param: vpnservice_id }
