heat_template_version: 2014-10-16

#
# you can deploy this template using the following command:
# 'openstack stack create -t example.yaml  <stackName>'
#

description: Simple template to deploy a single compute instance
  without external network (login will be possible through vnc console).

parameters:
 public_network_id:
   type: string
   default: caf8de33-1059-4473-a2c1-2a62d12294fa 

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: cirros 
      flavor: m1.small
      user_data_format: RAW
      networks:
        - port: { get_resource: example_port }

  example_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: example_net}

  example_net:
    type: OS::Neutron::Net
    properties: 
      name: example-net

  example_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: example_subnet
      dns_nameservers:
        - 37.123.105.116
        - 37.123.105.117
      network_id: {get_resource: example_net}
      ip_version: 4
      cidr: 10.0.0.0/24
      allocation_pools:
      - {start: 10.0.0.10, end: 10.0.0.250}

  example_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": { get_param: public_network_id }}

  router_subnet_connect:
    type: OS::Neutron::RouterInterface
    depends_on: [ example_subnet, example_router, example_net ]
    properties:
      router_id: { get_resource: example_router }
      subnet: { get_resource: example_subnet }


